---
EnableDefaultLinters: true
glob: "**/*.{html,text,js}{+*,}.erb"
exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'
linters:
  ErbSafety:
    enabled: false
    better_html_config: .better-html.yml
  RequireInputAutocomplete:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      # https://github.com/Shopify/erb-lint/#rubocop says the following:
      # "
      # Note: Each ruby statement (between ERB tags <% ... %>) is parsed and analyzed independently of each other.
      # Any rule that requires a broader context can trigger false positives (e.g. Lint/UselessAssignment will 
      # complaint for an assignment even if used in a subsequent ERB tag).
      # "
      # Suggested to disable there: {
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      # }
