name: Build Production Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
  
env:
  DOCKER_REGISTRY: ghcr.io/christopher-tiangco
  DOCKER_REPOSITORY: rails6.1

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_CACHE: /tmp/.buildx-cache
      BUILD_CACHE_NEW: /tmp/.buildx-cache-new
    steps:
      - uses: actions/checkout@v3
      
      - name: Set job environment variables
        run: |
          BUILD_DATETIME=$(date +'%Y-%m-%d_%H-%M-%S_UTC');
          echo "BUILD_DATETIME=$BUILD_DATETIME" >> $GITHUB_ENV;
          echo "IMAGE_TAG=learn-$BUILD_DATETIME" >> $GITHUB_ENV;

      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: ${{ env.BUILD_CACHE }}
          key: ${{ runner.os }}-buildx-${{ hashFiles('./Gemfile.lock', './yarn.lock') }}

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image, store to cache then push to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=local,src=${{ env.BUILD_CACHE }}
          cache-to: type=local,mode=max,dest=${{ env.BUILD_CACHE_NEW }}
          secrets: |
            "master_key=${{ secrets.RAILS_MASTER_KEY }}"
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}
          file: docker/Dockerfile
          target: production
      - name: Move Cache
        run: |
          rm -rf ${{ env.BUILD_CACHE }}
          mv ${{ env.BUILD_CACHE_NEW }} ${{ env.BUILD_CACHE }}
