name: Generate k8s secrets

on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

  workflow_dispatch:
env:
  TEMP_SECRETS_ENV_FILE: /home/runner/tmp-secrets
  SECRETS_JSON_FILE: /home/runner/secrets.json
jobs:
  generate_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Secrets file
        run: |
          echo "GHCR_TOKEN=${{ secrets.GHCR_TOKEN }} \
          RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}" >> ${{ env.TEMP_SECRETS_ENV_FILE }}
          echo ${{ env.TEMP_SECRETS_ENV_FILE }}


