name: K8s deployment

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

  workflow_dispatch:
  
env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_REPOSITORY: rails6.1
  K8S_NAMESPACE: learn-rails
  IMAGE: learn-2022-12-22_08-25-01_utc

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          
      - name: Deploy k8s services
        run: kubectl -n ${{ env.K8S_NAMESPACE }} apply -f k8s/learn-rails-app-svc.yaml

      - name: Deploy app
        run: |
          sed -i 's/{{ IMAGE }}/${{ env.DOCKER_REGISTRY}}\/${{ github.actor }}\/${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE }}/g' k8s/learn-rails-app-deployment.yaml
          kubectl -n ${{ env.K8S_NAMESPACE }} apply -f k8s/learn-rails-app-deployment.yaml